#!/bin/sh

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.

forced="--merged"

while getopts "h?f" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
    ;;
    f)  forced=""
    ;;
esac
done

# Deletes all merged branches except the current branch
git branch $forced | while read -r b; do 
if [[ "$b" =~ '* ' ]]; then
    echo "Skipping: $b"
elif [[ "$b" =~ '  (master|dev|develop|development|staging)' ]]; then
    echo "Skipping: $b"
else 
    printf "Delete $b: (y/n)? "
    read -n 1 choice </dev/tty
    shopt -s nocasematch
    if echo $choice | grep -i 'y'; then
        printf "*******"
        if [ -z "$forced" ]; then
            git branch -D $b
        else 
            git branch -d $b 
        fi
    else
        echo ""
    fi
fi
done
