#!/bin/sh

# get a list of all conflicted file names, returned with enclosing-quotes 
conflicted_files=($(git status --porcelain | grep 'UU\|AA' | cut -d' ' -f2 | awk '{print "\""$0"\""}'))
echo $conflicted_files
echo ${conflicted_files[0]}
echo ${conflicted_files[1]}
exit 1
for file in $conflicted_files
do
echo $file
echo "\n"
exit 1
    # open each conflicted file in vim
    $(git config --global core.editor) $file

    # ask user to commit file
    printf "Commit $file: (y/n)? "
    read -n 1 choice </dev/tty
    shopt -s nocasematch
    if echo $choice | grep -i 'y'; then
        xargs -o git add $file
    fi
    choice=''
done 

git status
echo "☢🚀  Don't forget to commit the results! ☢🚀 "
